name: GlassHelmet
version: '${project.version}'
main: jakkuhh.me.glashelmthing.GlassHelmetPlugin
api-version: 1.19
authors: [ jakuh ]
description:
  :heart: makes rainbow helm
website: jaack.host
commands:

